//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;

[assembly: AssemblyCompany("Azure's HQ")]
[assembly: AssemblyCopyright( "Copyright © Azure «(o.O)» (zollai@outlook.com) 2010-2021" )]
[assembly: AssemblyTrademark( "" )]

[assembly: AssemblyVersion("3.2021.0209.1318")]
//[assembly: AssemblyFileVersion("3.2021.0209.1318d")]
[assembly: AssemblyFileVersion("3.2021.0209.1318")]
