//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;

[assembly: AssemblyCompany("Azure «(o.O)»")]
[assembly: AssemblyCopyright( "Copyright © Azure «(o.O)» 2010-2019" )]
[assembly: AssemblyTrademark( "" )]

[assembly: AssemblyVersion("3.2019.0809.1252")]
//[assembly: AssemblyFileVersion("3.2019.0809.1252d")]
[assembly: AssemblyFileVersion("3.2019.0809.1252")]
