'
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'

Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices

<Assembly: AssemblyCompany("Azure's HQ")>
<Assembly: AssemblyCopyright("Copyright © Azure «(o.O)» (zollai@outlook.com) 2010-2021")>
<Assembly: AssemblyTrademark("")>
<Assembly: AssemblyVersion("3.2021.0502.1936")>
<Assembly: AssemblyFileVersion("3.2021.0502.1936")>

