'
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'

Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices

<Assembly: AssemblyCompany("Azure «(o.O)»")>
<Assembly: AssemblyCopyright("Copyright © Azure «(o.O)» 2010-2019")>
<Assembly: AssemblyTrademark("")>
<Assembly: AssemblyVersion("3.2019.0809.1252")>
<Assembly: AssemblyFileVersion("3.2019.0809.1252")>

