//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure.YAMP {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class yamp : global::System.Configuration.ApplicationSettingsBase {
        
        private static yamp defaultInstance = ((yamp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new yamp())));
        
        public static yamp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color VisColorBottom {
            get {
                return ((global::System.Drawing.Color)(this["VisColorBottom"]));
            }
            set {
                this["VisColorBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color VisColorTop {
            get {
                return ((global::System.Drawing.Color)(this["VisColorTop"]));
            }
            set {
                this["VisColorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color VisColorHold {
            get {
                return ((global::System.Drawing.Color)(this["VisColorHold"]));
            }
            set {
                this["VisColorHold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showPLEdit {
            get {
                return ((bool)(this["showPLEdit"]));
            }
            set {
                this["showPLEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Size sizeMainWindow {
            get {
                return ((global::System.Drawing.Size)(this["sizeMainWindow"]));
            }
            set {
                this["sizeMainWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationMainWindow {
            get {
                return ((global::System.Drawing.Point)(this["locationMainWindow"]));
            }
            set {
                this["locationMainWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lastPlayed.yspl")]
        public string lastPlayedList {
            get {
                return ((string)(this["lastPlayedList"]));
            }
            set {
                this["lastPlayedList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showTagForm {
            get {
                return ((bool)(this["showTagForm"]));
            }
            set {
                this["showTagForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Point locationTagForm {
            get {
                return ((global::System.Drawing.Point)(this["locationTagForm"]));
            }
            set {
                this["locationTagForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330, 335")]
        public global::System.Drawing.Point sizeTagForm {
            get {
                return ((global::System.Drawing.Point)(this["sizeTagForm"]));
            }
            set {
                this["sizeTagForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float opacity {
            get {
                return ((float)(this["opacity"]));
            }
            set {
                this["opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string lastFolder {
            get {
                return ((string)(this["lastFolder"]));
            }
            set {
                this["lastFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysOnTop {
            get {
                return ((bool)(this["alwaysOnTop"]));
            }
            set {
                this["alwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lastPlayedIndex {
            get {
                return ((int)(this["lastPlayedIndex"]));
            }
            set {
                this["lastPlayedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte VisualSetting {
            get {
                return ((byte)(this["VisualSetting"]));
            }
            set {
                this["VisualSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int VisTime {
            get {
                return ((int)(this["VisTime"]));
            }
            set {
                this["VisTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("103, 200, 255")]
        public global::System.Drawing.Color SeekBarColor {
            get {
                return ((global::System.Drawing.Color)(this["SeekBarColor"]));
            }
            set {
                this["SeekBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeekBarStyle {
            get {
                return ((bool)(this["SeekBarStyle"]));
            }
            set {
                this["SeekBarStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDigitFont {
            get {
                return ((bool)(this["UseDigitFont"]));
            }
            set {
                this["UseDigitFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float VolumeLevel {
            get {
                return ((float)(this["VolumeLevel"]));
            }
            set {
                this["VolumeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastKnownOutDevice {
            get {
                return ((int)(this["LastKnownOutDevice"]));
            }
            set {
                this["LastKnownOutDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 119, 134")]
        public global::System.Drawing.Color SeekBarBack {
            get {
                return ((global::System.Drawing.Color)(this["SeekBarBack"]));
            }
            set {
                this["SeekBarBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short TimeDisplayMode {
            get {
                return ((short)(this["TimeDisplayMode"]));
            }
            set {
                this["TimeDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size prevSizeMainWindow {
            get {
                return ((global::System.Drawing.Size)(this["prevSizeMainWindow"]));
            }
            set {
                this["prevSizeMainWindow"] = value;
            }
        }
    }
}
